<div data-bind="scope: 'product-list'">
<!-- ko template: getTemplate() --><!-- /ko -->
</div>
<script type="text/x-magento-init">
{
     "*": {
            "Magento_Ui/js/core/app": {
                "components": {
                    "product-list": {
                        "component": "Cardoso_CustomerProducts/js/product/validation-list",
                        "template" : "Cardoso_CustomerProducts/product_list/item"
                 }
             }
         }
     }
}
</script>
